import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav";
import Navmobile from "./components/navmobile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arem Project",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>      
        <Navmobile />
        {children}
        {/* Footer */}
      <footer className="text-center text-sm text-white py-4 bg-amber-950 border-t border-t-white">
        <p>
          © {new Date().getFullYear()} AREM | Bisnis Minuman Rempah Tradisional
        </p>
      </footer>
      </body>
    </html>
  );
}
